# Generated by Django 5.2.4 on 2025-07-19 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=100)),
                ('screen_type', models.CharField(blank=True, choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('ScreenX', 'ScreenX'), ('Other', 'Other')], default='2D', max_length=50, null=True)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='movies.theater')),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
                'ordering': ['theater__theater_name', 'screen_name'],
                'unique_together': {('theater', 'screen_name')},
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.screen')),
            ],
            options={
                'verbose_name': 'Showtime',
                'verbose_name_plural': 'Showtimes',
                'ordering': ['start_time', 'screen__theater__theater_name', 'screen__screen_name'],
                'unique_together': {('screen', 'start_time')},
            },
        ),
    ]
